name: FRWKV
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_kmp_llvm
  - addict=2.4.0=pyhd8ed1ab_2
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.6.1=h59595ed_0
  - attr=2.5.1=h166bdaf_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - cffi=1.17.1=py310h8deb56e_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - ffmpeg=6.0.1=gpl_h334edf3_100
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - gettext=0.25.1=h5888daf_0
  - gettext-tools=0.25.1=h5888daf_0
  - glib=2.84.2=h6287aef_0
  - glib-tools=2.84.2=h4833e2c_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h5888daf_0
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - harfbuzz=11.2.1=h3beb420_0
  - hdf5=1.14.3=nompi_h2d575fe_109
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jasper=4.2.5=h1920b20_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h1423503_5
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h8e693c7_0
  - libasprintf-devel=0.25.1=h8e693c7_0
  - libass=0.17.1=h39113c1_2
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=32_he106b2a_openblas
  - libclang-cpp20.1=20.1.7=default_h1df26ce_0
  - libclang13=20.1.7=default_he06ed0a_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h5888daf_0
  - libgettextpo-devel=0.25.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblapacke=3.9.0=32_he2f377e_openblas
  - libllvm20=20.1.7=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libopencv=4.8.1=py310h6ef52b8_5
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2023.1.0=h59595ed_2
  - libopenvino-auto-batch-plugin=2023.1.0=h59595ed_2
  - libopenvino-auto-plugin=2023.1.0=h59595ed_2
  - libopenvino-hetero-plugin=2023.1.0=h59595ed_2
  - libopenvino-intel-cpu-plugin=2023.1.0=h59595ed_2
  - libopenvino-intel-gpu-plugin=2023.1.0=h59595ed_2
  - libopenvino-ir-frontend=2023.1.0=h59595ed_2
  - libopenvino-onnx-frontend=2023.1.0=h59595ed_2
  - libopenvino-paddle-frontend=2023.1.0=h59595ed_2
  - libopenvino-pytorch-frontend=2023.1.0=h59595ed_2
  - libopenvino-tensorflow-frontend=2023.1.0=h59595ed_2
  - libopenvino-tensorflow-lite-frontend=2023.1.0=h59595ed_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h943b412_0
  - libpq=17.5=h27ae623_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.2=h6cd9bfd_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=257.7=h4e0b6ca_0
  - libtasn1=4.20.0=hb9d3cd8_0
  - libtiff=4.7.0=hf01ce69_5
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.7=h024ca30_0
  - lz4-c=1.10.0=h5888daf_1
  - magma=2.6.2=hc72dce7_0
  - mkl=2022.2.1=h6508926_16999
  - mmcv-full=1.7.0=cuda112py310h40cbac0_202
  - mpg123=1.32.9=hc50e24c_0
  - nccl=2.27.3.1=h03a54cd_0
  - ncurses=6.5=h2d0b736_3
  - nettle=3.9.1=h7ab15ed_0
  - nspr=4.36=h5888daf_0
  - nss=3.113=h159eef7_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - ocl-icd-system=1.0.0=1
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.1=h7b32b05_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre2=10.45=hc749103_0
  - pillow=11.3.0=py310h7e6dc6c_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.2=h29eaf8c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hac146a9_1
  - py-opencv=4.8.1=py310he6e113c_5
  - pycparser=2.22=pyh29332c3_1
  - python=3.10.18=hd6af730_0_cpython
  - python_abi=3.10=7_cp310
  - pyyaml=6.0.2=py310h89163eb_2
  - qt-main=5.15.15=hea1682b_4
  - readline=8.2=h8c095d6_2
  - sleef=3.8=h1b44611_0
  - snappy=1.1.10=hdb0a2a9_1
  - svt-av1=1.7.0=h59595ed_0
  - tbb=2021.13.0=hceb3a55_1
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.2.1=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yapf=0.43.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==45.0.4
      - cycler==0.12.1
      - filelock==3.14.0
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - grpcio==1.73.1
      - hf-xet==1.1.5
      - huggingface-hub==0.33.2
      - idna==3.10
      - jinja2==3.1.6
      - jmespath==0.10.0
      - kiwisolver==1.4.8
      - lightning-utilities==0.14.3
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mmcls==0.25.0
      - model-index==0.1.11
      - mpmath==1.3.0
      - multidict==6.6.3
      - natsort==8.4.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - numpy==1.24.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.0
      - prefetch-generator==1.0.3
      - propcache==0.3.2
      - protobuf==6.31.1
      - ptflops==0.6.9
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.2.5
      - pytorch-msssim==1.0.0
      - pytz==2023.4
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.5.3
      - setuptools==60.2.0
      - six==1.17.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - thop==0.1.1-2209072238
      - timm==1.0.16
      - torch==1.13.1+cu117
      - torchaudio==0.13.1
      - torchmetrics==1.5.2
      - torchvision==0.14.1+cu117
      - tqdm==4.65.2
      - triton==3.3.1
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - werkzeug==3.1.3
      - yarl==1.20.1
prefix: /Home/zlr/anaconda3/envs/FRWKV
