# Training configuration
TRAINING:
  VAL_AFTER_EVERY: 1
  SAVE_AFTER_EVERY: 200
  RESUME: False   # False
  PATCH_SIZE: 512
  TRAIN_DIR: '/data/home/zlr/Code/Hazydataset/NH-HAZE/train/'       # path to training data
  VAL_DIR: '/data/home/zlr/Code/Hazydataset/NH-HAZE/test/' # path to validation data
  SAVE_DIR: './checkpoints/'           # path to save models and images

TESTING:
  TEST_DIR: '/data/home/zlr/Code/Hazydataset/NH-HAZE/test/'